version: '3.8'
services:
  postgres:
    image: postgres:17.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U petclinic -d petclinic"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - petclinic-network
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  petclinic:
    image: ewennerberg/grafana-app-o11y-docker-swarm-spring-petclinic-petclinic:1.2
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/petclinic
      - SPRING_DATASOURCE_USERNAME=petclinic
      - SPRING_DATASOURCE_PASSWORD=petclinic
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
      - SPRING_PROFILES_ACTIVE=postgres
      - ALLOY_LOKI_URL=http://alloy:3100/loki/api/v1/push
    networks:
      - petclinic-network
    depends_on:
      - postgres
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  alloy:
    image: grafana/alloy:latest
    ports:
      - "3100:3100"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/alloy/config.alloy:/etc/alloy/config.alloy
    environment:
      - GRAFANACLOUD_METRICS_URL
      - GRAFANACLOUD_METRICS_USERNAME
      - GRAFANACLOUD_METRICS_PASSWORD
      - GRAFANACLOUD_LOGS_URL
      - GRAFANACLOUD_LOGS_USERNAME
      - GRAFANACLOUD_LOGS_PASSWORD
      - GRAFANACLOUD_FLEET_MANAGEMENT_URL
      - GRAFANACLOUD_FLEET_MANAGEMENT_USERNAME
      - GRAFANACLOUD_FLEET_MANAGEMENT_PASSWORD
    networks:
      - petclinic-network
    deploy:
      mode: global

networks:
  petclinic-network:
    driver: overlay
    attachable: true
